namespace Hire_Hop_Interface.Interface
{
    public static class Errors
    {
        #region Fields

        public static string[] errorStrings = new string[] {
    "Database error, please contact the HireHop team to report this.",
    "Connection error, please try again. ",
    "User not authorised to perform task.",
    "Missing parameters",
    "Request made to a job that is closed.",
    "Request made to a project that is closed.",
    "No action taken, could not find record",
    "Can't find job",
    "You can't perform this action with the current status.",
    "You are not logged in. Please <u><a href='/logout.php?d=1'>login</a></u> again.",
    "Record not found.",
    "You are not subscribed.<br>You are limited to what you can do unless you buy at least one user <a href='/settings.php?tab=1' target='_blank'>subscription</a>.",
    "Request made to a job that is locked.",
    "Can't accept changes with current status.",
    "Category is not empty. The category must have nothing inside it to be deleted (this includes deleted items).",
    "Too many autopull items. You are limited to 65",
    "No items were selected",
    "The selected stock item to assign the asset to is deleted.",
    "You are limited to adding 50 duplicates at a time",
    "Duplicate barcode, this barcode is already in use.",
    "No location on map set",
    "Nothing assigned to upload into.",
    "You have not subscribed to enough storage space to upload this file",
    "Nothing to upload",
    "File upload aborted",
    "No files found to delete",
    "EMAIL SENT, however:<br>HireHop could not connect to your email server sent box.",
    "EMAIL SENT, however:<br>HireHop was unable to save a copy of the email in your sent box.",
    "Email not found on server.",
    "Deleting this person will delete the company. Are you sure you want to delete?",
    "Only drafts or awaiting approval can be edited by you.",
    "Only drafts or awaiting approval can be deleted by you.",
    "The invoice needs to be authorised first.",
    "No email accounts have been setup.",
    "Archive not found.",
    "Nothing to archive.",
    "Archive not created as you are limited to 4 archives per job.",
    "Archive not created as you are limited to 30 archives per job.",
    "There are fewer of some items in the archive than have already been checked out.<br><b>Restore aborted!</b>",
    "Insufficient billed amounts specific to this job (credits will be more than billed).",
    "Insufficient billed amounts specific to this project (credits will be more than billed).",
    "Can't edit an authorised invoice or credit note.",
    "Package not found",
    "Too many items, you have reached the allowed limit.",
    "There are no editable autopulls.",
    "Can't do as requested as there is a locked node nested within the selection.",
    "Not supported on your browser.  Please update your browser.",
    "The items in the clipboard are not for your company.",
    "There are no chargeable items.",
    "Your edit means that there are fewer in the list than have already been checked out.",
    "Reserved assets conflict",
    "Colour already used",
    "Document load error",
    "You have reached the limit on calendar events you can add.",
    "Badly formatted barcode",
    ":title (:barcode) not available as it is on another <a href='/job.php?id=:job' target='_blank'>job</a>",
    ":title (:barcode) already checked.",
    "Unrecognised code (:barcode)",
    "Not enough available; :qty x :title",
    ":title not in list",
    "More than required; :qty x :title",
    "<a href='/modules/stock/equipment.php?asset=:asset_id' target='_blank'>:title (:barcode)</a> is damaged",
    ":title (:barcode) is not available",
    ":title is not from this job, but has been added to the pre-prep",
    "You are returning more :title than was checked out, however it has been added to the pre-prep",
    ":title is not from this job.",
    ":title is already checked in.",
    ":qty x :title - You are returning more than was checked out",
    "There were not any no codes out for :title.",
    "Can't connect to multi user sync. mode or connection was lost.",
    "The box must have at least a unique name or an item code",
    "Unknown barcode.",
    ":title (:barcode) has no required service.",
    ":title (:barcode) has no required PAT test.",
    ":title (:barcode) has no required test.",
    ":barcode is reserved for another job that conflicts with this one.",
    "The following reserved barcodes must be checked out for :title.<br>:txt",
    "User is already assigned to a resource.",
    "Contact is already assigned to a resource.",
    "Please confirm as changing job dates will causes item priority changes due to clashes with the following jobs:",
    "Job dates can't be changed as requested as this causes item priority clashes with the following jobs:",
    "Please confirm as changing the quantity will causes item priority changes due to clashes with the following jobs:",
    "The quantity can't be changed as requested as this causes item priority clashes with the following jobs:",
    "Can't cancel a job if there are still some open supplier purchase orders.",
    "Status already assigned.",
    "Parameter error.",
    "Password too short.",
    "Incorrect old password.",
    "Pre-Prep contains extra items not required on this job.",
    "Can't save assets to a virtual item.",
    "Can't edit an asset that is checked out.",
    "All payments and credit notes must be deleted first.",
    "Depot job error",
    "Depot project error",
    "Database allocation error",
    "Nothing to save",
    "Not a hire stock barcode.",
    "Quantity error.",
    "Number not found.",
    "Not found",
    "This is an internal hire and can only be edited from the receiving job.",
    "Making space error.",
    "Internal hire depot conflict.",
    "Date order error",
    "Note field empty",
    "You can only preprep to an item with an 'on shelf' status.",
    "No tax codes to import.",
    "Not a PDF file.",
    "Only drafts or awaiting approval can be edited.",
    "Purchase Order not found.",
    "Security warning, too many transactions",
    "Validation error",
    "You can only preprep items with 1 as the quantity.",
    "Already part of a pre-prep<br><b>(:barcode) :title<b>",
    ":barcode - Not a code for an asset.",
    "Already a box of a pre-prep<br><b>(:barcode) :title<b>",
    "Status changed, however you do not have permission to authorise the internal job,",
    "No tax codes to import.",
    "You do not have permission, contact your administrator.",
    "Bad data",
    "Names error",
    "Not valid Time zone",
    "Your administrator must set an export key first in Settings.",
    "You need more user licenses to have more active users.",
    "New value can't be higher than the old value.",
    "New value can't be lower than the old value.",
    "The new value is higher than the old value. Are you sure you want to save this?",
    "The new value is lower than the old value. Are you sure you want to save this?",
    "Payments exceed deposit value.",
    "Payments and credits exceed invoice value.",
    "Payments and credits exceed both invoice and deposit values.",
    "Can't delete the default price structure.",
    "Price structure already in use.",
    "These settings can only be changed by the Administrator.",
    "To change these settings you need to be in Administrator Mode.<br><br>To switch between Administrator and Normal Mode, click your name on the top right of the screen.",
    "Feature not supported by your server."
        };

        #endregion Fields
    }
}